//! Tests against EIP-7864 Python reference implementation test vectors.
//!
//! Vectors generated by `testgen/generate_vectors.py` using the exact
//! Python code from the EIP spec with BLAKE3 hashing.

use ethrex_binary_trie::key_mapping::{
    get_tree_key_for_basic_data, get_tree_key_for_code_chunk, get_tree_key_for_code_hash,
    get_tree_key_for_storage_slot, pack_basic_data,
};
use ethrex_binary_trie::merkle::merkelize;
use ethrex_binary_trie::trie::BinaryTrie;
use ethrex_common::{Address, U256};
use serde::Deserialize;

#[derive(Deserialize)]
#[serde(deny_unknown_fields)]
struct Insert {
    key: String,
    value: String,
}

#[derive(Deserialize)]
#[serde(deny_unknown_fields)]
struct TestVector {
    name: String,
    inserts: Vec<Insert>,
    expected_root: String,
    #[serde(default)]
    #[allow(dead_code)]
    note: String,
}

fn load_vectors_or_skip() -> Option<Vec<TestVector>> {
    let json = read_vector_file("test_vectors.json")?;
    Some(serde_json::from_str(&json).expect("failed to parse testgen/test_vectors.json"))
}

/// Read a JSON vector file from the binary-trie crate's `testgen/`, returning
/// `None` if it does not exist on disk. Vectors are git-ignored generated
/// artifacts; tests that depend on them skip-with-message when missing so a
/// checkout without Python+blake3 still passes `cargo test`.
///
/// Path resolves relative to this `test/` crate's manifest dir so the test
/// binary stays portable across the cwds cargo invokes it from.
fn read_vector_file(filename: &str) -> Option<String> {
    let path = format!(
        "{}/../crates/common/binary-trie/testgen/{}",
        env!("CARGO_MANIFEST_DIR"),
        filename
    );
    std::fs::read_to_string(&path).ok()
}

/// Macro for vector-based tests that should skip when the JSON is missing.
/// Prints a clear message so it's obvious in test output that coverage was
/// skipped, not that the test silently passed.
macro_rules! load_or_skip {
    ($filename:expr) => {
        match read_vector_file($filename) {
            Some(json) => json,
            None => {
                eprintln!(
                    "SKIP: testgen/{} not generated. Run `make binary-trie-vectors`.",
                    $filename
                );
                return;
            }
        }
    };
}

// ---------------------------------------------------------------------------
// Task 2.5 helpers
// ---------------------------------------------------------------------------

fn parse_address(s: &str) -> Address {
    let s = s.strip_prefix("0x").unwrap_or(s);
    let bytes = hex::decode(s).expect("invalid address hex");
    assert_eq!(
        bytes.len(),
        20,
        "address must be 20 bytes, got {}",
        bytes.len()
    );
    Address::from_slice(&bytes)
}

fn parse_u256_hex32(s: &str) -> U256 {
    let bytes = hex::decode(s).expect("invalid U256 hex");
    assert_eq!(
        bytes.len(),
        32,
        "U256 must be 32 bytes, got {}",
        bytes.len()
    );
    U256::from_big_endian(&bytes)
}

// ---------------------------------------------------------------------------
// Task 2.5 — Account vector JSON schema
// ---------------------------------------------------------------------------

#[derive(Deserialize)]
#[serde(deny_unknown_fields)]
struct AccountOp {
    op: String,
    #[serde(default)]
    address: String,
    #[serde(default)]
    version: u8,
    #[serde(default)]
    code_size: u32,
    #[serde(default)]
    nonce: u64,
    /// 32-byte big-endian hex string for balance
    #[serde(default)]
    balance: String,
    /// 32-byte hex for code_hash
    #[serde(default)]
    code_hash: String,
}

#[derive(Deserialize)]
#[serde(deny_unknown_fields)]
struct AccountVector {
    name: String,
    ops: Vec<AccountOp>,
    expected_root: String,
    #[serde(default)]
    #[allow(dead_code)]
    note: String,
}

/// Apply all ops in an `AccountVector` to a `BinaryTrie`.
///
/// Supported ops:
///   `set_basic_data` — pack and insert the basic_data leaf
///   `set_code_hash`  — insert the code_hash leaf
///   `clear_stem`     — remove all 256 sub-indices of the base stem
fn apply_account_ops(trie: &mut BinaryTrie, ops: &[AccountOp], vector_name: &str) {
    for (i, op) in ops.iter().enumerate() {
        match op.op.as_str() {
            "set_basic_data" => {
                let addr = parse_address(&op.address);
                let balance = parse_u256_hex32(&op.balance);
                let packed = pack_basic_data(op.version, op.code_size, op.nonce, balance);
                let key = get_tree_key_for_basic_data(&addr);
                trie.insert(key, packed).unwrap_or_else(|e| {
                    panic!(
                        "vector '{}' op {i} (set_basic_data {}): insert failed: {e}",
                        vector_name, op.address
                    )
                });
            }
            "set_code_hash" => {
                let addr = parse_address(&op.address);
                let code_hash = hex_to_32(&op.code_hash);
                let key = get_tree_key_for_code_hash(&addr);
                trie.insert(key, code_hash).unwrap_or_else(|e| {
                    panic!(
                        "vector '{}' op {i} (set_code_hash {}): insert failed: {e}",
                        vector_name, op.address
                    )
                });
            }
            "clear_stem" => {
                let addr = parse_address(&op.address);
                // The base stem covers sub-indices 0-255 at tree_index=0.
                // Remove all 256 possible sub-indices to clear the stem.
                for sub_index in 0u8..=255 {
                    let key = get_tree_key_for_basic_data(&addr);
                    // Build the stem key: first 31 bytes from basic_data key + sub_index.
                    let mut stem_key = key;
                    stem_key[31] = sub_index;
                    trie.remove(stem_key).unwrap_or_else(|e| {
                        panic!(
                            "vector '{}' op {i} (clear_stem {} sub_index={sub_index}): remove failed: {e}",
                            vector_name, op.address
                        )
                    });
                }
            }
            other => panic!(
                "vector '{}' op {i}: unknown account op '{other}'",
                vector_name
            ),
        }
    }
}

// ---------------------------------------------------------------------------
// Task 2.5 — Storage vector JSON schema
// ---------------------------------------------------------------------------

#[derive(Deserialize)]
#[serde(deny_unknown_fields)]
struct StorageOp {
    op: String,
    address: String,
    /// 32-byte big-endian hex for slot number
    slot: String,
    /// 32-byte big-endian hex for value; all-zeros means deletion (zero-write)
    value: String,
}

#[derive(Deserialize)]
#[serde(deny_unknown_fields)]
struct StorageVector {
    name: String,
    ops: Vec<StorageOp>,
    expected_root: String,
}

fn apply_storage_ops(trie: &mut BinaryTrie, ops: &[StorageOp], vector_name: &str) {
    for (i, op) in ops.iter().enumerate() {
        assert_eq!(
            op.op, "set_storage",
            "vector '{}' op {i}: expected 'set_storage', got '{}'",
            vector_name, op.op
        );
        let addr = parse_address(&op.address);
        let slot = parse_u256_hex32(&op.slot);
        let value = hex_to_32(&op.value);
        let key = get_tree_key_for_storage_slot(&addr, slot);
        if value == [0u8; 32] {
            // Zero-write = delete the slot.
            trie.remove(key).unwrap_or_else(|e| {
                panic!(
                    "vector '{}' op {i} (set_storage zero-write slot {}): remove failed: {e}",
                    vector_name, op.slot
                )
            });
        } else {
            trie.insert(key, value).unwrap_or_else(|e| {
                panic!(
                    "vector '{}' op {i} (set_storage slot {}): insert failed: {e}",
                    vector_name, op.slot
                )
            });
        }
    }
}

// ---------------------------------------------------------------------------
// Task 2.5 — Code-chunk vector JSON schema
// ---------------------------------------------------------------------------

#[derive(Deserialize)]
#[serde(deny_unknown_fields)]
struct CodeChunkOp {
    op: String,
    address: String,
    chunk_id: u64,
    /// 32-byte hex for chunk value (1 leading byte + 31 code bytes)
    value: String,
}

#[derive(Deserialize)]
#[serde(deny_unknown_fields)]
struct CodeChunkVector {
    name: String,
    ops: Vec<CodeChunkOp>,
    expected_root: String,
}

fn apply_codechunk_ops(trie: &mut BinaryTrie, ops: &[CodeChunkOp], vector_name: &str) {
    for (i, op) in ops.iter().enumerate() {
        assert_eq!(
            op.op, "set_code_chunk",
            "vector '{}' op {i}: expected 'set_code_chunk', got '{}'",
            vector_name, op.op
        );
        let addr = parse_address(&op.address);
        let value = hex_to_32(&op.value);
        let key = get_tree_key_for_code_chunk(&addr, op.chunk_id);
        trie.insert(key, value).unwrap_or_else(|e| {
            panic!(
                "vector '{}' op {i} (set_code_chunk chunk_id={}): insert failed: {e}",
                vector_name, op.chunk_id
            )
        });
    }
}

// ---------------------------------------------------------------------------
// Task 2.6 — Negative-case vector JSON schema
// ---------------------------------------------------------------------------

#[derive(Deserialize)]
#[serde(deny_unknown_fields)]
struct NegativeOp {
    op: String,
    #[serde(default)]
    key: String,
    #[serde(default)]
    value: String,
    /// For clear_stem_raw: 31-byte hex stem
    #[serde(default)]
    stem: String,
}

#[derive(Deserialize)]
#[serde(deny_unknown_fields)]
struct NegativeVector {
    name: String,
    ops: Vec<NegativeOp>,
    probe_key: String,
    expected_root: String,
    expected_absent: bool,
    expected_value: Option<String>,
    #[serde(default)]
    #[allow(dead_code)]
    note: String,
}

fn apply_negative_ops(trie: &mut BinaryTrie, ops: &[NegativeOp], vector_name: &str) {
    for (i, op) in ops.iter().enumerate() {
        match op.op.as_str() {
            "insert_raw" => {
                let key = hex_to_32(&op.key);
                let value = hex_to_32(&op.value);
                trie.insert(key, value).unwrap_or_else(|e| {
                    panic!(
                        "vector '{}' op {i} (insert_raw): insert failed: {e}",
                        vector_name
                    )
                });
            }
            "clear_stem_raw" => {
                // Stem is 31 bytes hex.
                let stem_bytes = hex::decode(&op.stem).expect("invalid stem hex");
                assert_eq!(stem_bytes.len(), 31, "stem must be 31 bytes");
                // Remove all 256 sub-indices.
                for sub_index in 0u8..=255 {
                    let mut key = [0u8; 32];
                    key[..31].copy_from_slice(&stem_bytes);
                    key[31] = sub_index;
                    trie.remove(key).unwrap_or_else(|e| {
                        panic!(
                            "vector '{}' op {i} (clear_stem_raw sub_index={sub_index}): remove failed: {e}",
                            vector_name
                        )
                    });
                }
            }
            other => panic!(
                "vector '{}' op {i}: unknown negative op '{other}'",
                vector_name
            ),
        }
    }
}

fn hex_to_32(s: &str) -> [u8; 32] {
    let bytes = hex::decode(s).expect("invalid hex");
    assert_eq!(bytes.len(), 32, "expected 32 bytes, got {}", bytes.len());
    let mut arr = [0u8; 32];
    arr.copy_from_slice(&bytes);
    arr
}

#[test]
fn eip7864_reference_vectors() {
    let Some(vectors) = load_vectors_or_skip() else {
        eprintln!("SKIP: testgen/test_vectors.json not generated. Run `make binary-trie-vectors`.");
        return;
    };
    assert!(!vectors.is_empty(), "no test vectors loaded");

    for vector in &vectors {
        let mut trie = BinaryTrie::new();
        for ins in &vector.inserts {
            let key = hex_to_32(&ins.key);
            let value = hex_to_32(&ins.value);
            trie.insert(key, value)
                .unwrap_or_else(|e| panic!("insert failed for vector '{}': {e}", vector.name));
        }

        let root = merkelize(&mut trie);
        let expected = hex_to_32(&vector.expected_root);

        assert_eq!(
            root,
            expected,
            "vector '{}': root mismatch\n  got:      {}\n  expected: {}",
            vector.name,
            hex::encode(root),
            vector.expected_root
        );
    }
}

#[test]
fn eip7864_insertion_order_independence() {
    let Some(vectors) = load_vectors_or_skip() else {
        eprintln!("SKIP: testgen/test_vectors.json not generated. Run `make binary-trie-vectors`.");
        return;
    };
    let vector = vectors
        .iter()
        .find(|v| v.name == "insertion_order_independence")
        .expect("missing insertion_order_independence vector");

    // Insert in forward order
    let mut t1 = BinaryTrie::new();
    for ins in &vector.inserts {
        t1.insert(hex_to_32(&ins.key), hex_to_32(&ins.value))
            .unwrap();
    }

    // Insert in reverse order
    let mut t2 = BinaryTrie::new();
    for ins in vector.inserts.iter().rev() {
        t2.insert(hex_to_32(&ins.key), hex_to_32(&ins.value))
            .unwrap();
    }

    let root1 = merkelize(&mut t1);
    let root2 = merkelize(&mut t2);
    assert_eq!(root1, root2, "insertion order should not affect root");
    assert_eq!(root1, hex_to_32(&vector.expected_root));
}

/// Verify that proofs for every key in each test vector verify against
/// the Python-validated root. Since the roots are cross-validated with the
/// reference implementation, correct proof verification implies correct
/// proof generation.
#[test]
fn eip7864_proofs_verify_against_reference_roots() {
    let Some(vectors) = load_vectors_or_skip() else {
        eprintln!("SKIP: testgen/test_vectors.json not generated. Run `make binary-trie-vectors`.");
        return;
    };

    for vector in &vectors {
        let mut trie = BinaryTrie::new();
        // Use a map so overwrites keep only the latest value per key.
        let mut keys: std::collections::HashMap<[u8; 32], [u8; 32]> =
            std::collections::HashMap::new();
        for ins in &vector.inserts {
            let key = hex_to_32(&ins.key);
            let value = hex_to_32(&ins.value);
            trie.insert(key, value).unwrap();
            keys.insert(key, value);
        }

        let root = merkelize(&mut trie);
        let expected = hex_to_32(&vector.expected_root);
        assert_eq!(root, expected, "root mismatch for '{}'", vector.name);

        // Prove every inserted key and verify against the reference root.
        for (key, value) in &keys {
            let proof = trie.get_proof(*key).unwrap_or_else(|e| {
                panic!(
                    "get_proof failed for vector '{}', key {}: {e}",
                    vector.name,
                    hex::encode(key)
                )
            });
            assert_eq!(
                proof.value,
                Some(*value),
                "vector '{}': proof value mismatch for key {}",
                vector.name,
                hex::encode(key)
            );
            assert!(
                proof.verify(root, *key),
                "vector '{}': proof failed verification for key {}",
                vector.name,
                hex::encode(key)
            );
        }

        // Also prove an absent key and verify.
        let mut absent_key = [0xFFu8; 32];
        absent_key[0] = 0xFE; // unlikely to collide with test stems
        let absent_proof = trie.get_proof(absent_key).unwrap();
        assert!(absent_proof.value.is_none());
        assert!(
            absent_proof.verify(root, absent_key),
            "vector '{}': absence proof failed verification",
            vector.name
        );
    }
}

// ---------------------------------------------------------------------------
// Task 2.5 — Three new vector test functions
// ---------------------------------------------------------------------------

/// Deserialize `vectors_accounts.json`, apply each op sequence to a `BinaryTrie`,
/// and compare the computed root against the Python-generated expected root.
///
/// Operations: `set_basic_data`, `set_code_hash`, `clear_stem`.
#[test]
fn verify_accounts_vectors() {
    let json = load_or_skip!("vectors_accounts.json");
    let json = json.as_str();
    let vectors: Vec<AccountVector> =
        serde_json::from_str(json).expect("failed to parse vectors_accounts.json");
    assert!(!vectors.is_empty(), "no account vectors loaded");

    for vector in &vectors {
        let mut trie = BinaryTrie::new();
        apply_account_ops(&mut trie, &vector.ops, &vector.name);

        let root = merkelize(&mut trie);
        let expected = hex_to_32(&vector.expected_root);

        assert_eq!(
            root,
            expected,
            "account vector '{}': root mismatch\n  got:      {}\n  expected: {}",
            vector.name,
            hex::encode(root),
            vector.expected_root,
        );
    }
}

/// Deserialize `vectors_storage.json`, apply each op sequence to a `BinaryTrie`,
/// and compare the computed root against the Python-generated expected root.
///
/// Operations: `set_storage` (value all-zeros = zero-write / delete).
#[test]
fn verify_storage_vectors() {
    let json = load_or_skip!("vectors_storage.json");
    let json = json.as_str();
    let vectors: Vec<StorageVector> =
        serde_json::from_str(json).expect("failed to parse vectors_storage.json");
    assert!(!vectors.is_empty(), "no storage vectors loaded");

    for vector in &vectors {
        let mut trie = BinaryTrie::new();
        apply_storage_ops(&mut trie, &vector.ops, &vector.name);

        let root = merkelize(&mut trie);
        let expected = hex_to_32(&vector.expected_root);

        assert_eq!(
            root,
            expected,
            "storage vector '{}': root mismatch\n  got:      {}\n  expected: {}",
            vector.name,
            hex::encode(root),
            vector.expected_root,
        );
    }
}

/// Deserialize `vectors_codechunk.json`, apply each op sequence to a `BinaryTrie`,
/// and compare the computed root against the Python-generated expected root.
///
/// Operations: `set_code_chunk`.  Tests boundary chunk IDs 0, 1, 127, 128, 1000, 1023
/// and a full 0-1023 contiguous contract.
#[test]
fn verify_codechunk_vectors() {
    let json = load_or_skip!("vectors_codechunk.json");
    let json = json.as_str();
    let vectors: Vec<CodeChunkVector> =
        serde_json::from_str(json).expect("failed to parse vectors_codechunk.json");
    assert!(!vectors.is_empty(), "no code-chunk vectors loaded");

    for vector in &vectors {
        let mut trie = BinaryTrie::new();
        apply_codechunk_ops(&mut trie, &vector.ops, &vector.name);

        let root = merkelize(&mut trie);
        let expected = hex_to_32(&vector.expected_root);

        assert_eq!(
            root,
            expected,
            "codechunk vector '{}': root mismatch\n  got:      {}\n  expected: {}",
            vector.name,
            hex::encode(root),
            vector.expected_root,
        );
    }
}

// ---------------------------------------------------------------------------
// Task 2.6 — Negative-case vectors
//
// Three absence-proof shapes: same-stem-absent-subindex, different-stem-absent,
// empty-child-absent.
// Two selfdestruct-then-recreated cases.
// ---------------------------------------------------------------------------

/// Deserialize `vectors_negative.json` and verify:
///   - absence proofs: proof.value is None, proof.verify() returns true
///   - presence proofs (recreated accounts): proof.value matches expected_value,
///     proof.verify() returns true
#[test]
fn verify_negative_vectors() {
    let json = load_or_skip!("vectors_negative.json");
    let json = json.as_str();
    let vectors: Vec<NegativeVector> =
        serde_json::from_str(json).expect("failed to parse vectors_negative.json");
    assert!(!vectors.is_empty(), "no negative vectors loaded");

    for vector in &vectors {
        let mut trie = BinaryTrie::new();
        apply_negative_ops(&mut trie, &vector.ops, &vector.name);

        let root = merkelize(&mut trie);
        let expected_root = hex_to_32(&vector.expected_root);

        assert_eq!(
            root,
            expected_root,
            "negative vector '{}': root mismatch\n  got:      {}\n  expected: {}",
            vector.name,
            hex::encode(root),
            vector.expected_root,
        );

        let probe_key = hex_to_32(&vector.probe_key);
        let proof = trie.get_proof(probe_key).unwrap_or_else(|e| {
            panic!(
                "negative vector '{}': get_proof failed for probe_key {}: {e}",
                vector.name, vector.probe_key
            )
        });

        if vector.expected_absent {
            assert!(
                proof.value.is_none(),
                "negative vector '{}': expected absence but proof.value = {:?}",
                vector.name,
                proof.value.map(hex::encode)
            );
        } else {
            let expected_val = hex_to_32(vector.expected_value.as_deref().unwrap_or_else(|| {
                panic!(
                    "negative vector '{}': expected_absent=false but expected_value is null",
                    vector.name
                )
            }));
            assert_eq!(
                proof.value,
                Some(expected_val),
                "negative vector '{}': proof.value mismatch\n  got:      {:?}\n  expected: {}",
                vector.name,
                proof.value.map(hex::encode),
                hex::encode(expected_val),
            );
        }

        assert!(
            proof.verify(root, probe_key),
            "negative vector '{}': proof.verify() returned false for probe_key {}",
            vector.name,
            vector.probe_key
        );
    }
}
