{
 "title": "Ethrex L2 - Overview",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "L2 Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Current Block Number",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "block_number", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Transactions in mempool",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mempool_tx_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "OnChainProposer Status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "l2_blocks_tracker{block_type=\"lastCommittedBatch\"}",
     "legendFormat": "Last Committed Batch"
    },
    {
     "expr": "l2_blocks_tracker{block_type=\"lastCommittedBlock\"}",
     "legendFormat": "Last Committed Block"
    },
    {
     "expr": "l2_blocks_tracker{block_type=\"lastVerifiedBatch\"}",
     "legendFormat": "Last Verified Batch"
    },
    {
     "expr": "l2_blocks_tracker{block_type=\"lastVerifiedBlock\"}",
     "legendFormat": "Last Verified Block"
    }
   ]
  },
  {
   "title": "Block gas limit",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "gas_limit", "legendFormat": "__auto" }
   ]
  },
  { "title": "Batch Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Batch Verification Gas",
   "type": "xychart",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "batch_verification_gas", "legendFormat": "Batch Verification Gas" }
   ]
  },
  {
   "title": "Batch Proving Time",
   "type": "xychart",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "batch_proving_time", "legendFormat": "Batch Proving Time" }
   ]
  },
  {
   "title": "Batch Gas Used",
   "type": "xychart",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "batch_gas_used", "legendFormat": "Batch Gas Used" }
   ]
  },
  {
   "title": "Batch Commitment Gas",
   "type": "xychart",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "batch_commitment_gas", "legendFormat": "Batch Commitment Gas" }
   ]
  },
  {
   "title": "Batch Gas Used vs. Proving Time",
   "type": "xychart",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expr": "batch_proving_time", "legendFormat": "Batch Proving Time" },
    { "expr": "batch_gas_used", "legendFormat": "Batch Proving Time" }
   ]
  },
  {
   "title": "Batch Transaction Count",
   "type": "xychart",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "batch_tx_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Batch Commitment Blob Gas",
   "type": "xychart",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "batch_commitment_blob_gas", "legendFormat": "Batch Commitment Gas" }
   ]
  },
  {
   "title": "Batch Transaction Count vs. Proving Time",
   "type": "xychart",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expr": "batch_proving_time", "legendFormat": "Batch Proving Time" },
    { "expr": "batch_tx_count", "legendFormat": "Batch Proving Time" }
   ]
  },
  {
   "title": "Batch Size",
   "type": "xychart",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "batch_size", "legendFormat": "__auto" }
   ]
  },
  { "title": "Gas Prices", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "L1 Gas Price",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "Gwei" } },
   "targets": [
    { "expr": "l1_gas_price / 1000000000", "legendFormat": "L1 Gas Price" }
   ]
  },
  {
   "title": "L2 Gas Price",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "Gwei" } },
   "targets": [
    { "expr": "l2_gas_price / 1000000000", "legendFormat": "L2 Gas Price" }
   ]
  },
  { "title": "Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Last Blob Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "l2_blob_usage", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Blob Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "l2_blob_usage", "legendFormat": "Blob Usage" }
   ]
  },
  { "title": "Operations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "Historical Committed Operations",
   "type": "stat",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 53 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "l2_operations_tracker{operations_type=\"processedPrivilegedTransactions\"}",
     "legendFormat": "Processed Privileged Transactions"
    },
    {
     "expr": "l2_operations_tracker{operations_type=\"processedMessages\"}",
     "legendFormat": "Processed Messages"
    }
   ]
  },
  { "title": "Accounts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 } },
  {
   "title": "L1 Committer Balance",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "ETH" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "parser": "backend",
     "root_selector": "$.result",
     "source": "url",
     "type": "json",
     "url_options": {
      "body_content_type": "application/json",
      "body_type": "raw",
      "data": "{\n  \"jsonrpc\": \"2.0\",\n  \"id\": \"1\",\n  \"method\": \"eth_getBalance\",\n  \"params\": [\"0xC932b62A827417748E8eda76d415BD2aF523Bd14\", \"latest\"]\n}",
      "method": "POST"
     }
    }
   ]
  },
  {
   "title": "L1 Proof Sender Balance",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "ETH" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "parser": "backend",
     "root_selector": "$.result",
     "source": "url",
     "type": "json",
     "url_options": {
      "body_content_type": "application/json",
      "body_type": "raw",
      "data": "{\n  \"jsonrpc\": \"2.0\",\n  \"id\": \"1\",\n  \"method\": \"eth_getBalance\",\n  \"params\": [\"0x30ebBfbE91Edea22BFA99b16c2E9F74C29eF7cfe\", \"latest\"]\n}",
      "method": "POST"
     }
    }
   ]
  }
 ]
}