{
 "title": "Ethrex L2 - Overview",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "L2 Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Current Block Number",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "block_number", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "OnChainProposer Status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "l2_blocks_tracker{block_type!=\"lastFetchedL1Block\"}",
     "legendFormat": "{{block_type}}"
    }
   ]
  },
  {
   "title": "Gas Price",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    { "expr": "l2_gas_price", "legendFormat": "__auto" }
   ]
  },
  { "title": "Usage Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Last Blob Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "l2_blob_usage", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Blob Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 5, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "l2_blob_usage", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Last Block Gas Limit Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "gas_limit", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Gas Limit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "gas_limit", "legendFormat": "__auto" }
   ]
  },
  { "title": "Transaction Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Mempool",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "mempool_tx_count{type=\"regular\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "l2_operations_tracker", "legendFormat": "{{operations_type}}" }
   ]
  },
  {
   "title": "Status of Transactions",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "transactions_tracker", "legendFormat": "{{tx_type}} || {{status}}" }
   ]
  },
  {
   "title": "TPS",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "transactions_per_second", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Transactions",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "transactions_tracker", "legendFormat": "{{tx_type}} || {{status}}" }
   ]
  }
 ]
}