{
 "title": "Ethrex - Transactions",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Total Transactions",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "transactions_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total Transactions Per Second",
   "type": "timeseries",
   "description": "Simple demo\n",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(transactions_total[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Succeeded Transactions By Type",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "transactions_tracker{status=\"succedded\"}",
     "legendFormat": "{{tx_type}}"
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 5, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "transactions_tracker", "legendFormat": "{{tx_type}} || {{status}}" }
   ]
  },
  {
   "title": "Status of Transactions",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "transactions_tracker", "legendFormat": "{{tx_type}} || {{status}}" }
   ]
  }
 ]
}