use bytes::Bytes;
use ethrex_l2_common::prover::{BatchProof, ProofFormat, ProverType};
use serde::{Deserialize, Serialize};

/// Generic enum for the ProverServer <--> ProverClient Communication Protocol.
///
/// The type parameter `I` represents the input type sent from server to prover:
/// - L2 uses `ProverInputData`
/// - L1 uses `ProgramInput`
#[allow(clippy::large_enum_variant)]
#[derive(Serialize, Deserialize)]
pub enum ProofData<I> {
    /// 1.
    /// The client performs any needed setup steps
    /// This includes things such as key registration
    ProverSetup {
        prover_type: ProverType,
        payload: Bytes,
    },

    /// 2.
    /// The Server acknowledges the receipt of the setup and it's completion
    ProverSetupACK,

    /// 3.
    /// The Client initiates the connection with a BatchRequest.
    /// Asking for the input the prover_server considers/needs.
    /// The commit hash is used to ensure the client and server are compatible.
    /// The prover_type tells the coordinator which backend the client runs,
    /// so it can skip batches that already have a proof for that type.
    BatchRequest {
        commit_hash: String,
        prover_type: ProverType,
    },

    /// 4.
    /// The Server responds with VersionMismatch when the prover's code version
    /// does not match the version needed to prove the next batch. This can happen
    /// when the batch was stored with a different version, or when the prover is
    /// stale and future batches will use a newer version.
    VersionMismatch,

    /// 4b.
    /// The Server responds with ProverTypeNotNeeded when the connecting prover's
    /// backend type is not in the set of required proof types for this deployment.
    ProverTypeNotNeeded { prover_type: ProverType },

    /// 5.
    /// The Server responds with a BatchResponse containing the input data.
    /// If the BatchResponse is ProofData::BatchResponse{None, None, None},
    /// the Client knows the BatchRequest couldn't be performed.
    BatchResponse {
        batch_number: Option<u64>,
        input: Option<I>,
        format: Option<ProofFormat>,
    },

    /// 6.
    /// The Client submits the zk Proof generated by the prover for the specified batch.
    ProofSubmit {
        batch_number: u64,
        batch_proof: BatchProof,
    },

    /// 7.
    /// The Server acknowledges the receipt of the proof and updates its state,
    ProofSubmitACK { batch_number: u64 },
}

impl<I> ProofData<I> {
    /// Builder function for creating a ProverSetup
    pub fn prover_setup(prover_type: ProverType, payload: Bytes) -> Self {
        ProofData::ProverSetup {
            prover_type,
            payload,
        }
    }

    /// Builder function for creating a ProverSetupACK
    pub fn prover_setup_ack() -> Self {
        ProofData::ProverSetupACK
    }

    /// Builder function for creating a BatchRequest
    pub fn batch_request(commit_hash: String, prover_type: ProverType) -> Self {
        ProofData::BatchRequest {
            commit_hash,
            prover_type,
        }
    }

    /// Builder function for creating a VersionMismatch
    pub fn version_mismatch() -> Self {
        ProofData::VersionMismatch
    }

    /// Builder function for creating a BatchResponse
    pub fn batch_response(batch_number: u64, input: I, format: ProofFormat) -> Self {
        ProofData::BatchResponse {
            batch_number: Some(batch_number),
            input: Some(input),
            format: Some(format),
        }
    }

    pub fn empty_batch_response() -> Self {
        ProofData::BatchResponse {
            batch_number: None,
            input: None,
            format: None,
        }
    }

    /// Builder function for creating a ProofSubmit
    pub fn proof_submit(batch_number: u64, batch_proof: BatchProof) -> Self {
        ProofData::ProofSubmit {
            batch_number,
            batch_proof,
        }
    }

    /// Builder function for creating a ProofSubmitAck
    pub fn proof_submit_ack(batch_number: u64) -> Self {
        ProofData::ProofSubmitACK { batch_number }
    }
}
