//! Tests against EIP-7864 Python reference implementation test vectors.
//!
//! Vectors generated by `testgen/generate_vectors.py` using the exact
//! Python code from the EIP spec with BLAKE3 hashing.

use ethrex_binary_trie::merkle::merkelize;
use ethrex_binary_trie::trie::BinaryTrie;
use serde::Deserialize;

#[derive(Deserialize)]
struct Insert {
    key: String,
    value: String,
}

#[derive(Deserialize)]
struct TestVector {
    name: String,
    inserts: Vec<Insert>,
    expected_root: String,
}

fn load_vectors() -> Vec<TestVector> {
    let json = include_str!("test_vectors.json");
    serde_json::from_str(json).expect("failed to parse test_vectors.json")
}

fn hex_to_32(s: &str) -> [u8; 32] {
    let bytes = hex::decode(s).expect("invalid hex");
    assert_eq!(bytes.len(), 32, "expected 32 bytes, got {}", bytes.len());
    let mut arr = [0u8; 32];
    arr.copy_from_slice(&bytes);
    arr
}

#[test]
fn eip7864_reference_vectors() {
    let vectors = load_vectors();
    assert!(!vectors.is_empty(), "no test vectors loaded");

    for vector in &vectors {
        let mut trie = BinaryTrie::new();
        for ins in &vector.inserts {
            let key = hex_to_32(&ins.key);
            let value = hex_to_32(&ins.value);
            trie.insert(key, value)
                .unwrap_or_else(|e| panic!("insert failed for vector '{}': {e}", vector.name));
        }

        let root = merkelize(&mut trie);
        let expected = hex_to_32(&vector.expected_root);

        assert_eq!(
            root,
            expected,
            "vector '{}': root mismatch\n  got:      {}\n  expected: {}",
            vector.name,
            hex::encode(root),
            vector.expected_root
        );
    }
}

#[test]
fn eip7864_insertion_order_independence() {
    let vectors = load_vectors();
    let vector = vectors
        .iter()
        .find(|v| v.name == "insertion_order_independence")
        .expect("missing insertion_order_independence vector");

    // Insert in forward order
    let mut t1 = BinaryTrie::new();
    for ins in &vector.inserts {
        t1.insert(hex_to_32(&ins.key), hex_to_32(&ins.value))
            .unwrap();
    }

    // Insert in reverse order
    let mut t2 = BinaryTrie::new();
    for ins in vector.inserts.iter().rev() {
        t2.insert(hex_to_32(&ins.key), hex_to_32(&ins.value))
            .unwrap();
    }

    let root1 = merkelize(&mut t1);
    let root2 = merkelize(&mut t2);
    assert_eq!(root1, root2, "insertion order should not affect root");
    assert_eq!(root1, hex_to_32(&vector.expected_root));
}

/// Verify that proofs for every key in each test vector verify against
/// the Python-validated root. Since the roots are cross-validated with the
/// reference implementation, correct proof verification implies correct
/// proof generation.
#[test]
fn eip7864_proofs_verify_against_reference_roots() {
    let vectors = load_vectors();

    for vector in &vectors {
        let mut trie = BinaryTrie::new();
        // Use a map so overwrites keep only the latest value per key.
        let mut keys: std::collections::HashMap<[u8; 32], [u8; 32]> =
            std::collections::HashMap::new();
        for ins in &vector.inserts {
            let key = hex_to_32(&ins.key);
            let value = hex_to_32(&ins.value);
            trie.insert(key, value).unwrap();
            keys.insert(key, value);
        }

        let root = merkelize(&mut trie);
        let expected = hex_to_32(&vector.expected_root);
        assert_eq!(root, expected, "root mismatch for '{}'", vector.name);

        // Prove every inserted key and verify against the reference root.
        for (key, value) in &keys {
            let proof = trie.get_proof(*key).unwrap_or_else(|e| {
                panic!(
                    "get_proof failed for vector '{}', key {}: {e}",
                    vector.name,
                    hex::encode(key)
                )
            });
            assert_eq!(
                proof.value,
                Some(*value),
                "vector '{}': proof value mismatch for key {}",
                vector.name,
                hex::encode(key)
            );
            assert!(
                proof.verify(root, *key),
                "vector '{}': proof failed verification for key {}",
                vector.name,
                hex::encode(key)
            );
        }

        // Also prove an absent key and verify.
        let mut absent_key = [0xFFu8; 32];
        absent_key[0] = 0xFE; // unlikely to collide with test stems
        let absent_proof = trie.get_proof(absent_key).unwrap();
        assert!(absent_proof.value.is_none());
        assert!(
            absent_proof.verify(root, absent_key),
            "vector '{}': absence proof failed verification",
            vector.name
        );
    }
}
