{
 "title": "Ethrex L1 - Perf Dashboard",
 "time": { "from": "now-10m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(eth_con_beacon_slot,instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Execution Client",
   "type": "stat",
   "gridPos": { "h": 3, "w": 9, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (version)(eth_exe_web3_client_version{instance=~\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Consensus Config",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "eth_con_spec_config_name{instance=~\"$instance\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Consensus Fork",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "eth_con_fork_current{instance=~\"$instance\"}",
     "legendFormat": "{{fork}}"
    }
   ]
  },
  {
   "title": "Gas Used %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expr": "gas_used", "legendFormat": "__auto" },
    { "expr": "gas_limit", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 6, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "Ggas/s" } },
   "targets": [
    { "expr": "gigagas", "legendFormat": "Gigagas/s" }
   ]
  },
  {
   "title": "Block Height",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 3 },
   "targets": [
    { "expr": "block_number", "legendFormat": "BlockNumber" }
   ]
  },
  {
   "title": "Panel Title",
   "type": "xychart",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 11 },
   "targets": [
    { "expr": "block_number", "legendFormat": "Block Number" },
    { "expr": "gigagas", "legendFormat": "Gigagas/s" },
    { "expr": "gas_used", "legendFormat": "Gas Used" },
    { "expr": "gas_limit", "legendFormat": "Gas Limit" }
   ]
  }
 ]
}