use ethrex_common::{H256, U256};
use ethrex_l2_sdk::calldata::Value;
use serde::{Deserialize, Serialize};
use std::fmt::{Debug, Display};

/// Enum used to identify the different proving systems.
#[derive(Debug, Clone, Copy, Hash, PartialEq, Eq, Serialize, Deserialize)]
pub enum ProverType {
    Exec,
    RISC0,
    SP1,
    Pico,
    Aligned,
}

impl ProverType {
    /// Used to iterate through all the possible proving systems
    pub fn all() -> impl Iterator<Item = ProverType> {
        [
            ProverType::Exec,
            ProverType::RISC0,
            ProverType::SP1,
            ProverType::Pico,
        ]
        .into_iter()
    }

    /// Used to get the empty_calldata structure for that specific prover
    /// It has to match the `OnChainProposer.sol` verify() function
    pub fn empty_calldata(&self) -> Vec<Value> {
        match self {
            ProverType::RISC0 => {
                vec![
                    Value::Bytes(vec![].into()),
                    Value::FixedBytes(H256::zero().to_fixed_bytes().to_vec().into()),
                    Value::FixedBytes(H256::zero().to_fixed_bytes().to_vec().into()),
                ]
            }
            ProverType::SP1 => {
                vec![Value::Bytes(vec![].into()), Value::Bytes(vec![].into())]
            }
            ProverType::Pico => {
                vec![
                    Value::FixedBytes(H256::zero().as_bytes().to_vec().into()),
                    Value::Bytes(vec![].into()),
                    Value::FixedArray(vec![Value::Uint(U256::zero()); 8]),
                ]
            }
            ProverType::Exec => unimplemented!("Doesn't need to generate an empty calldata."),
            ProverType::Aligned => {
                panic!("We don't need this method for Aligned");
            }
        }
    }

    pub fn verifier_getter(&self) -> Option<String> {
        // These values have to match with the OnChainProposer.sol contract
        match self {
            Self::RISC0 => Some("R0VERIFIER()".to_string()),
            Self::SP1 => Some("SP1VERIFIER()".to_string()),
            Self::Pico => Some("PICOVERIFIER()".to_string()),
            Self::Exec => None,
            // TODO: review this
            Self::Aligned => None,
        }
    }
}

impl Display for ProverType {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Exec => write!(f, "Exec"),
            Self::RISC0 => write!(f, "RISC0"),
            Self::SP1 => write!(f, "SP1"),
            Self::Pico => write!(f, "Pico"),
            Self::Aligned => write!(f, "Aligned"),
        }
    }
}

/// Contains the proof data recently created by the prover.
/// It can be either a `ProofCalldata` ready to be sent to the on-chain verifier or a `ProofBytes`
/// to be sent to Aligned.
#[derive(PartialEq, Serialize, Deserialize, Clone, Debug)]
pub enum BatchProof {
    ProofCalldata(ProofCalldata),
    ProofBytes(ProofBytes),
}

impl BatchProof {
    pub fn prover_type(&self) -> ProverType {
        match self {
            BatchProof::ProofCalldata(proof) => proof.prover_type,
            BatchProof::ProofBytes(_) => ProverType::Aligned,
        }
    }

    pub fn calldata(&self) -> Vec<Value> {
        match self {
            BatchProof::ProofCalldata(proof) => proof.calldata.clone(),
            BatchProof::ProofBytes(_) => vec![],
        }
    }

    pub fn proof(&self) -> Vec<u8> {
        match self {
            BatchProof::ProofCalldata(_) => vec![],
            BatchProof::ProofBytes(proof) => proof.proof.clone(),
        }
    }
}

/// Contains the Proof and the public values generated by the prover.
/// It is used to send the proof to Aligned.
#[derive(PartialEq, Serialize, Deserialize, Clone, Debug)]
pub struct ProofBytes {
    pub proof: Vec<u8>,
    pub public_values: Vec<u8>,
}

/// Contains the data ready to be sent to the on-chain verifiers.
#[derive(PartialEq, Serialize, Deserialize, Clone, Debug)]
pub struct ProofCalldata {
    pub prover_type: ProverType,
    pub calldata: Vec<Value>,
}
