"use client";

import { useState, useEffect } from "react";
import { useParams } from "next/navigation";
import Link from "next/link";
import { deploymentsApi } from "@/lib/api";
import { useAuth } from "@/components/auth-provider";
import { Deployment } from "@/lib/types";
import { DeploymentStatusBadge } from "@/components/deployment-status";

const DESKTOP_DOWNLOAD_URL = "https://github.com/tokamak-network/ethrex/releases";

function parseConfig(deployment: Deployment): { mode: string; l1Image: string } {
  try {
    const parsed = deployment.config ? JSON.parse(deployment.config) : {};
    return { mode: parsed.mode || "local", l1Image: parsed.l1Image || "ethrex" };
  } catch {
    return { mode: "local", l1Image: "ethrex" };
  }
}

function generateTomlConfig(deployment: Deployment): string {
  const slug = deployment.program_slug || deployment.program_id;
  return `# App Registry Configuration
# Generated by Tokamak App Store for: ${deployment.name}

default_program = "${slug}"
enabled_programs = ["${slug}"]
`;
}

function downloadFile(content: string, filename: string, type: string) {
  const blob = new Blob([content], { type });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

export default function DeploymentDetailPage() {
  const params = useParams();
  const { user } = useAuth();
  const [deployment, setDeployment] = useState<Deployment | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");

  useEffect(() => {
    if (!params.id || !user) return;
    deploymentsApi
      .get(params.id as string)
      .then(setDeployment)
      .catch((err) => setError(err instanceof Error ? err.message : "Failed to load"))
      .finally(() => setLoading(false));
  }, [params.id, user]);

  if (!user) {
    return (
      <div className="max-w-4xl mx-auto px-4 py-16 text-center">
        <Link href="/login" className="text-blue-600 hover:underline">Login required</Link>
      </div>
    );
  }

  if (loading) {
    return (
      <div className="min-h-[60vh] flex items-center justify-center">
        <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-blue-600" />
      </div>
    );
  }

  if (error || !deployment) {
    return (
      <div className="max-w-4xl mx-auto px-4 py-16 text-center">
        <h1 className="text-xl font-bold text-red-600 mb-4">L2 Not Found</h1>
        <p className="text-gray-600 mb-4">{error}</p>
        <Link href="/deployments" className="text-blue-600 hover:underline">Back to My L2s</Link>
      </div>
    );
  }

  const config = parseConfig(deployment);

  return (
    <div className="max-w-4xl mx-auto px-4 py-8">
      <Link href="/deployments" className="text-blue-600 hover:underline text-sm mb-4 inline-block">
        &larr; Back to My L2s
      </Link>

      {/* Header */}
      <div className="bg-white rounded-xl shadow-sm border p-6 mb-6">
        <div className="flex items-start justify-between">
          <div>
            <h1 className="text-2xl font-bold">{deployment.name}</h1>
            <p className="text-gray-500 mt-1">
              App: {deployment.program_name || deployment.program_slug}
              {deployment.category && (
                <span className="ml-2 px-2 py-0.5 bg-gray-100 rounded text-xs">{deployment.category}</span>
              )}
            </p>
          </div>
          <DeploymentStatusBadge phase={deployment.phase} />
        </div>
      </div>

      {/* Desktop App CTA */}
      <div className="bg-blue-50 border border-blue-200 rounded-xl p-6 mb-6">
        <h2 className="text-lg font-semibold text-blue-800 mb-2">Manage with Desktop App</h2>
        <p className="text-sm text-blue-700 mb-4">
          Deployment, monitoring, logs, and lifecycle management are handled by the Tokamak Desktop App.
          Install it to deploy, start, stop, and manage your L2 chain.
        </p>
        <a
          href={DESKTOP_DOWNLOAD_URL}
          target="_blank"
          rel="noopener noreferrer"
          className="inline-flex items-center gap-2 px-4 py-2 bg-blue-600 text-white rounded-lg text-sm font-medium hover:bg-blue-700"
        >
          <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
            <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"/>
            <polyline points="7 10 12 15 17 10"/>
            <line x1="12" y1="15" x2="12" y2="3"/>
          </svg>
          Get Desktop App
        </a>
      </div>

      {/* Info */}
      <div className="space-y-6">
        <div className="bg-white rounded-xl border p-6">
          <h2 className="text-lg font-semibold mb-4">Configuration</h2>
          <dl className="space-y-3 text-sm">
            <div className="flex justify-between">
              <dt className="text-gray-500">Chain ID</dt>
              <dd className="font-medium">{deployment.chain_id || "Not set"}</dd>
            </div>
            <div className="flex justify-between">
              <dt className="text-gray-500">Mode</dt>
              <dd className="font-medium capitalize">{config.mode}</dd>
            </div>
            <div className="flex justify-between">
              <dt className="text-gray-500">App</dt>
              <dd className="font-medium">{deployment.program_slug}</dd>
            </div>
            <div className="flex justify-between">
              <dt className="text-gray-500">Created</dt>
              <dd className="font-medium">{new Date(deployment.created_at).toLocaleString()}</dd>
            </div>
            {(deployment.bridge_address || deployment.proposer_address) && (
              <>
                {deployment.bridge_address && (
                  <div className="flex justify-between">
                    <dt className="text-gray-500">Bridge</dt>
                    <dd className="font-mono text-xs">{deployment.bridge_address}</dd>
                  </div>
                )}
                {deployment.proposer_address && (
                  <div className="flex justify-between">
                    <dt className="text-gray-500">OnChainProposer</dt>
                    <dd className="font-mono text-xs">{deployment.proposer_address}</dd>
                  </div>
                )}
              </>
            )}
          </dl>
        </div>

        {/* Manual setup guide */}
        <div className="bg-white rounded-xl border p-6">
          <h2 className="text-lg font-semibold mb-3">Manual Setup (CLI)</h2>
          <p className="text-sm text-gray-600 mb-4">
            You can also run this L2 manually using the ethrex CLI.
          </p>
          <div className="flex gap-2 mb-4">
            <button
              onClick={() => downloadFile(generateTomlConfig(deployment), "programs.toml", "application/toml")}
              className="px-3 py-1.5 border border-gray-300 rounded-lg text-sm hover:bg-gray-50"
            >
              Download programs.toml
            </button>
          </div>
          <div className="bg-gray-50 rounded-lg p-4 text-sm space-y-3">
            <div>
              <p className="font-medium text-gray-700 mb-1">1. Clone & build</p>
              <pre className="bg-gray-900 text-gray-100 rounded p-2 text-xs">
{`git clone https://github.com/tokamak-network/ethrex.git
cd ethrex`}
              </pre>
            </div>
            <div>
              <p className="font-medium text-gray-700 mb-1">2. Run with app</p>
              <pre className="bg-gray-900 text-gray-100 rounded p-2 text-xs">
{`make -C crates/l2 init-guest-program PROGRAM=${deployment.program_slug || deployment.program_id}`}
              </pre>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
